# Program Planning Committee {-}

## Carrie Brown {-}

## Bruce Desmarais {-}

Bruce Desmarais is the DeGrandis-McCourtney Early Career Professor in Political Science, Director of the [Center for Social Data Analytics](https://soda.la.psu.edu), and a co-hire of the [Institute for Computational and Data Sciences](https://icds.psu.edu) at Penn State University. His research is focused on methodological development and applications that further our understanding of the complex interdependence that underlies politics and public policy. Methodologically, he focuses on methods for modeling networks, analyzing text, and running experiments on social systems. Primary application areas of interest to Bruce include public policy diffusion and digital communications involving political elites.

## Rick Gilmore {-}

Rick is Professor of [Psychology](https://psych.la.psu.edu) and Director of the Open Data and Developmental Science (ODDS) initiative with the [Penn State Child Study Center (CSC)](https://csc.la.psu.edu). He co-founded and co-directs the [Databrary](https://databrary.org) data repository, and serves as Co-PI on the [Play & Learning Across a Year (PLAY) Project](https://play-project.org). His research examines the development of perception and action in infants, children, and adults using behavioral, neural, and computational methods.

## Frank Hillary {-}

## Nicole Lazar {-}

## Daisy Lei {-}

Daisy Lei is a PhD candidate at Penn State, pursuing a dual-title degree in Psychology and Language Science. She is in Dr. Janet van Hell's Bilingualism and Language Development (BiLD) Lab. Her research interests include native- and nonnative-accented speech processing and word learning in monolinguals and bilinguals. She uses behavioral and neuropsychological (EEG) measurements in her research.

## Kevin McManus {-}

Kevin McManus is an Associate Professor of [Applied Linguistics](https://aplng.la.psu.edu) at Penn State, Director of the [Center for Language Acquisition](https://language.la.psu.edu), and Director of the [Center for Advanced Language Proficiency, Education, and Research](https://calper.la.psu.edu). His research focuses on second language acquisition, especially psycholinguistics, crosslinguistic influence, and instruction, and research methodology, including replication research and open science. 

## Hollie Mullin {-}

## Jenae Neiderhiser {-}

## Alaina Pearce {-}

[Alaina Pearce](https://sites.psu.edu/alainapearce/) is an Assistant Research Professor of [Nutritional Sciences](https://hhd.psu.edu/nutrition) and the [Center for Childhood Obesity Research](https://hhd.psu.edu/ccor) at Penn State. She is also affiliated with the [Child Study Center](https://csc.la.psu.edu/research/collaborative-research-initiatives/), the [Center on Rural Education and Communities](https://ed.psu.edu/academics/departments/department-education-policy-studies/eps-centers-councils-and-journals/center-rural-education-and-communities), and the [Institute for Compuational and Data Sciences](https://www.icds.psu.edu). Her research centers on examining neurocognitive and behavioral factors that contribute to risk and resiliency for pediatric obesity.

## Briana Wham {-}
